### ISSUE TITLE
Не оч заебись что эксепшан назван bad request exeption. Напоминаю, что сервис ничего не должен знать о том, кто его вызывает, поэтому эксепшан должен называться так, как это видит сервис - нет сущности эксепшан или такая сущность уже есть эксепшан и т.п.

### ISSUE THREAD

**Issue by asavochkin** [TMNova/WebApplication#1]
https://github.com/TMNova/WebApplication/blob/7eb656692a14365d094e694268f71024caa6a433/src/main/java/ru/lanit/web/services/PersonService.java#L33

**Comment by asavochkin** [comment]
Вообще тут получается смешение слоев. надо развязаться.

**Comment by TMNova** [comment]
Готово. Разделил на слои все эксепшены, опубликовано в новом коммите
