### ISSUE TITLE
Сделай плиз еще тест например на PersonService, где у тебя не будет мокбинов и вообще моков. Репозиторий пусть тоже будет настоящим. И ты сначала через репу создаешь что надо в БД, а потом проверяешь что методы сервиса отрабатывают как надо

### ISSUE THREAD

**Issue by asavochkin** [TMNova/WebApplication#4]
https://github.com/TMNova/WebApplication/blob/7eb656692a14365d094e694268f71024caa6a433/src/test/java/ru/lanit/web/services/PersonServiceTest.java#L22

**Comment by TMNova** [comment]
Добавил в новом комите PersonServiceInMemoryTest
